#define S                                1
#define ATKEYWORD                        2
#define SEMI                             3
#define LBRACE                           4
#define RBRACE                           5
#define COMMA                            6
#define PLUS                             7
#define GT                               8
#define IDENT                            9
#define ASTERISK                        10
#define HASH                            11
#define DOT                             12
#define LBRAC                           13
#define RBRAC                           14
#define EQUALS                          15
#define STRING                          16
#define INCLUDES                        17
#define DASHMATCH                       18
#define PREFIX                          19
#define SUFFIX                          20
#define SUBSTR                          21
#define COLON                           22
#define FUNCTION                        23
#define RPAREN                          24
#define DELIM                           25
#define NUMBER                          26
#define PERCENTAGE                      27
#define DIMENSION                       28
#define URI                             29
#define UNICODE_RANGE                   30
#define LPAREN                          31
