/* This file is automatically generated by Lemon from input grammar
** source file "parser.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 400 "parser.y"

#include <assert.h>
#include <string.h>
#include <strings.h>
#define CSS_INTERNALS
#include "css/css.h"
#include "utils/utils.h" 
#line 37 "parser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef S
#define S                               1
#define ATKEYWORD                       2
#define SEMI                            3
#define LBRACE                          4
#define RBRACE                          5
#define COMMA                           6
#define PLUS                            7
#define GT                              8
#define IDENT                           9
#define ASTERISK                       10
#define HASH                           11
#define DOT                            12
#define LBRAC                          13
#define RBRAC                          14
#define EQUALS                         15
#define STRING                         16
#define INCLUDES                       17
#define DASHMATCH                      18
#define PREFIX                         19
#define SUFFIX                         20
#define SUBSTR                         21
#define COLON                          22
#define FUNCTION                       23
#define RPAREN                         24
#define DELIM                          25
#define NUMBER                         26
#define PERCENTAGE                     27
#define DIMENSION                      28
#define URI                            29
#define UNICODE_RANGE                  30
#define LPAREN                         31
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    css_parser_TOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is css_parser_TOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    css_parser_ARG_SDECL     A static variable declaration for the %extra_argument
**    css_parser_ARG_PDECL     A parameter declaration for the %extra_argument
**    css_parser_ARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    css_parser_ARG_STORE     Code to store %extra_argument into yypParser
**    css_parser_ARG_FETCH     Code to extract %extra_argument from yypParser
**    css_parser_CTX_*         As css_parser_ARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 55
#define YYACTIONTYPE unsigned short int
#define css_parser_TOKENTYPE  struct css_parser_token 
typedef union {
  int yyinit;
  css_parser_TOKENTYPE yy0;
  struct css_selector * yy17;
  struct css_node * yy50;
  css_combinator yy57;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define css_parser_ARG_SDECL  struct css_parser_params *param ;
#define css_parser_ARG_PDECL , struct css_parser_params *param 
#define css_parser_ARG_PARAM ,param 
#define css_parser_ARG_FETCH  struct css_parser_params *param =yypParser->param ;
#define css_parser_ARG_STORE yypParser->param =param ;
#define css_parser_CTX_SDECL
#define css_parser_CTX_PDECL
#define css_parser_CTX_PARAM
#define css_parser_CTX_FETCH
#define css_parser_CTX_STORE
#define YYNSTATE             128
#define YYNRULE              91
#define YYNRULE_WITH_ACTION  73
#define YYNTOKEN             32
#define YY_MAX_SHIFT         127
#define YY_MIN_SHIFTREDUCE   200
#define YY_MAX_SHIFTREDUCE   290
#define YY_ERROR_ACTION      291
#define YY_ACCEPT_ACTION     292
#define YY_NO_ACTION         293
#define YY_MIN_REDUCE        294
#define YY_MAX_REDUCE        384
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (420)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   367,  276,   73,  381,    3,   69,  266,  268,  269,   83,
 /*    10 */    82,   81,  102,   25,  311,   22,  254,  259,  261,  262,
 /*    20 */   263,  264,   86,   66,  276,  255,  251,  252,  253,  256,
 /*    30 */   258,   64,   68,   67,   71,   70,  266,  268,  269,  250,
 /*    40 */   272,  257,  267,   63,  305,   22,  254,  259,  261,  262,
 /*    50 */   263,  264,  265,   66,  339,  255,  251,  252,  253,  256,
 /*    60 */   258,   64,  266,  268,  269,   99,  272,  257,  267,   63,
 /*    70 */    72,   71,  254,  259,  261,  262,  263,  264,  265,   66,
 /*    80 */   377,   78,  251,  252,  253,  256,  258,   64,  266,  268,
 /*    90 */   269,   21,  272,  257,  267,   63,   49,   48,  254,  259,
 /*   100 */   261,  262,  263,  264,  265,   66,  242,  255,  251,  252,
 /*   110 */   253,  256,  258,   64,  266,  268,  269,  250,  272,  257,
 /*   120 */   267,   63,   59,  219,  254,  259,  261,  262,  263,  264,
 /*   130 */   265,   66,   55,  255,  251,  252,  253,  256,  258,   64,
 /*   140 */   127,  373,  373,  373,   52,  336,    1,   51,  101,    2,
 /*   150 */   103,    8,  300,   55,   23,  307,   22,  312,  292,   80,
 /*   160 */   312,  126,  312,  312,  312,   24,  336,  312,  312,  312,
 /*   170 */   309,  233,   87,  309,   85,  309,  309,  309,  312,   10,
 /*   180 */   309,  309,  309,  308,  234,   27,  308,    7,  308,  308,
 /*   190 */   308,  309,  276,  308,  308,  308,  124,    9,  300,   65,
 /*   200 */    23,  307,   22,  232,  308,  368,  368,   29,  368,  368,
 /*   210 */   368,  368,  368,  276,   28,  338,   55,  338,  343,  220,
 /*   220 */    45,   65,   42,   39,   36,   33,   30,   46,   57,  214,
 /*   230 */   215,  218,  118,   47,   51,   26,   88,  335,   51,   32,
 /*   240 */    89,  335,   91,  231,  122,   54,   31,  230,  122,   54,
 /*   250 */   235,   51,  229,  121,  335,   51,  125,  100,  335,   65,
 /*   260 */   342,  122,   54,   65,  277,  122,   54,  369,  228,  369,
 /*   270 */   369,  369,  301,  227,   23,  307,   22,  218,  118,   47,
 /*   280 */   123,  226,   98,   65,   85,   84,   53,  126,   91,   77,
 /*   290 */   238,   75,   65,  126,   11,   35,  126,    7,  104,  225,
 /*   300 */   126,   90,   34,  126,  105,  106,  126,  126,   92,  107,
 /*   310 */   126,  126,  108,   93,  126,  126,  109,  110,  126,  126,
 /*   320 */   260,   94,  111,  126,  126,  112,   95,  126,  126,  224,
 /*   330 */   113,  114,  126,  126,   96,  115,  126,  126,  116,   97,
 /*   340 */   126,  126,  117,  303,  126,  126,  302,    6,  126,  126,
 /*   350 */    12,   74,  126,  126,  270,   13,  119,  126,  126,   14,
 /*   360 */   340,  126,  126,  223,   76,   15,  126,  126,  120,    4,
 /*   370 */   126,  126,  295,    5,  126,  126,   16,   17,  126,  126,
 /*   380 */    18,   19,  126,  126,  383,  382,  126,  126,  222,  380,
 /*   390 */   378,  126,  126,   79,  294,  126,  126,   56,   20,   71,
 /*   400 */   126,  238,  238,  203,  202,   38,   41,  221,  238,   44,
 /*   410 */    61,   58,   37,   40,  277,   62,   43,   50,  271,   60,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */     0,    1,    2,   40,    4,   42,    6,    7,    8,    9,
 /*    10 */    10,   11,   12,   13,   50,   51,   16,   17,   18,   19,
 /*    20 */    20,   21,   22,   23,    1,   25,   26,   27,   28,   29,
 /*    30 */    30,   31,    2,    3,    4,    5,    6,    7,    8,    9,
 /*    40 */    10,   11,   12,   13,   50,   51,   16,   17,   18,   19,
 /*    50 */    20,   21,   22,   23,   40,   25,   26,   27,   28,   29,
 /*    60 */    30,   31,    6,    7,    8,    9,   10,   11,   12,   13,
 /*    70 */     3,    4,   16,   17,   18,   19,   20,   21,   22,   23,
 /*    80 */    40,   25,   26,   27,   28,   29,   30,   31,    6,    7,
 /*    90 */     8,    9,   10,   11,   12,   13,    7,    8,   16,   17,
 /*   100 */    18,   19,   20,   21,   22,   23,    9,   25,   26,   27,
 /*   110 */    28,   29,   30,   31,    6,    7,    8,    9,   10,   11,
 /*   120 */    12,   13,   53,    9,   16,   17,   18,   19,   20,   21,
 /*   130 */    22,   23,   42,   25,   26,   27,   28,   29,   30,   31,
 /*   140 */    35,   36,   37,   38,   54,    1,   34,   42,   43,    4,
 /*   150 */    45,   46,   47,   42,   49,   50,   51,    1,   32,   33,
 /*   160 */     4,   35,    6,    7,    8,   54,   22,   11,   12,   13,
 /*   170 */     1,    9,   33,    4,   35,    6,    7,    8,   22,   41,
 /*   180 */    11,   12,   13,    1,   24,   23,    4,   48,    6,    7,
 /*   190 */     8,   22,    1,   11,   12,   13,   39,   46,   47,   42,
 /*   200 */    49,   50,   51,   14,   22,   14,   15,    9,   17,   18,
 /*   210 */    19,   20,   21,    1,   16,    3,   42,    5,   39,   14,
 /*   220 */    15,   42,   17,   18,   19,   20,   21,    9,   54,    9,
 /*   230 */    10,   11,   12,   13,   42,    9,   44,   45,   42,    9,
 /*   240 */    44,   45,   22,   14,   52,   53,   16,   14,   52,   53,
 /*   250 */    24,   42,   14,   44,   45,   42,   39,   44,   45,   42,
 /*   260 */    39,   52,   53,   42,    1,   52,   53,    4,   14,    6,
 /*   270 */     7,    8,   47,   14,   49,   50,   51,   11,   12,   13,
 /*   280 */    39,   14,   33,   42,   35,   33,   22,   35,   22,   39,
 /*   290 */     3,   33,   42,   35,   33,    9,   35,   48,   33,   14,
 /*   300 */    35,   33,   16,   35,   33,   33,   35,   35,   33,   33,
 /*   310 */    35,   35,   33,   33,   35,   35,   33,   33,   35,   35,
 /*   320 */    24,   33,   33,   35,   35,   33,   33,   35,   35,   14,
 /*   330 */    33,   33,   35,   35,   33,   33,   35,   35,   33,   33,
 /*   340 */    35,   35,   33,   33,   35,   35,   33,   33,   35,   35,
 /*   350 */    33,   33,   35,   35,   24,   33,   33,   35,   35,   33,
 /*   360 */    33,   35,   35,   14,   33,   33,   35,   35,   33,   33,
 /*   370 */    35,   35,   33,   33,   35,   35,   33,   33,   35,   35,
 /*   380 */    33,   33,   35,   35,   33,   33,   35,   35,   14,   33,
 /*   390 */    33,   35,   35,   33,   33,   35,   35,    2,   33,    4,
 /*   400 */    35,    3,    3,    5,    5,    9,    9,   14,    3,    9,
 /*   410 */     5,   22,   16,   16,    1,    4,   16,    6,   14,    3,
 /*   420 */    55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
 /*   430 */    55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
 /*   440 */    55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
 /*   450 */    55,   55,
};
#define YY_SHIFT_COUNT    (127)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (416)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */    23,    0,   56,   56,   56,   56,  220,  220,   23,   23,
 /*    10 */    30,   82,  108,  108,  108,  108,  108,  108,  108,  108,
 /*    20 */   108,  191,  266,  266,  212,   23,   23,   23,   23,   23,
 /*    30 */    23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
 /*    40 */    23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
 /*    50 */    23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
 /*    60 */    23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
 /*    70 */    23,   23,   23,   23,  395,  395,  395,   67,   97,  420,
 /*    80 */   420,  156,  169,  182,  205,  263,  162,   89,  398,  399,
 /*    90 */   226,  162,  198,  230,  286,  396,  397,  400,   89,  144,
 /*   100 */   405,  411,  114,  145,  160,  189,  229,  233,  238,  254,
 /*   110 */   259,  267,  285,  315,  349,  374,  393,  218,  114,  264,
 /*   120 */   389,  287,  416,  296,  404,  330,  413,  413,
};
#define YY_REDUCE_COUNT (80)
#define YY_REDUCE_MIN   (-37)
#define YY_REDUCE_MAX   (365)
static const short yy_reduce_ofst[] = {
 /*     0 */   126,  105,  192,  196,  209,  213,  151,  225,  139,  249,
 /*    10 */   -37,  157,  179,   90,  111,  174,  157,  217,  221,  241,
 /*    20 */   250,  252,  -36,   -6,  258,  261,  265,  268,  271,  272,
 /*    30 */   275,  276,  279,  280,  283,  284,  288,  289,  292,  293,
 /*    40 */   297,  298,  301,  302,  305,  306,  252,  309,  310,  313,
 /*    50 */   314,  317,  318,  322,  323,  326,  327,  331,  332,  335,
 /*    60 */   336,  339,  340,  343,  344,  347,  348,  351,  352,  356,
 /*    70 */   357,  360,  361,  365,   14,   14,   14,   40,   69,  138,
 /*    80 */   112,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   368,  291,  330,  330,  330,  330,  291,  291,  368,  368,
 /*    10 */   291,  341,  341,  291,  337,  291,  341,  341,  341,  341,
 /*    20 */   341,  344,  310,  306,  368,  368,  368,  368,  368,  368,
 /*    30 */   368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
 /*    40 */   368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
 /*    50 */   368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
 /*    60 */   368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
 /*    70 */   368,  368,  368,  368,  334,  291,  384,  291,  349,  379,
 /*    80 */   372,  351,  366,  344,  291,  304,  359,  298,  291,  291,
 /*    90 */   291,  291,  291,  291,  291,  291,  291,  291,  299,  344,
 /*   100 */   291,  291,  361,  291,  291,  291,  291,  291,  291,  291,
 /*   110 */   291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
 /*   120 */   291,  333,  331,  291,  291,  291,  369,  374,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  css_parser_ARG_SDECL                /* A place to hold %extra_argument */
  css_parser_CTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void css_parser_Trace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "S",
  /*    2 */ "ATKEYWORD",
  /*    3 */ "SEMI",
  /*    4 */ "LBRACE",
  /*    5 */ "RBRACE",
  /*    6 */ "COMMA",
  /*    7 */ "PLUS",
  /*    8 */ "GT",
  /*    9 */ "IDENT",
  /*   10 */ "ASTERISK",
  /*   11 */ "HASH",
  /*   12 */ "DOT",
  /*   13 */ "LBRAC",
  /*   14 */ "RBRAC",
  /*   15 */ "EQUALS",
  /*   16 */ "STRING",
  /*   17 */ "INCLUDES",
  /*   18 */ "DASHMATCH",
  /*   19 */ "PREFIX",
  /*   20 */ "SUFFIX",
  /*   21 */ "SUBSTR",
  /*   22 */ "COLON",
  /*   23 */ "FUNCTION",
  /*   24 */ "RPAREN",
  /*   25 */ "DELIM",
  /*   26 */ "NUMBER",
  /*   27 */ "PERCENTAGE",
  /*   28 */ "DIMENSION",
  /*   29 */ "URI",
  /*   30 */ "UNICODE_RANGE",
  /*   31 */ "LPAREN",
  /*   32 */ "stylesheet",
  /*   33 */ "ws",
  /*   34 */ "statement_list",
  /*   35 */ "ws_1",
  /*   36 */ "statement",
  /*   37 */ "ruleset",
  /*   38 */ "at_rule",
  /*   39 */ "any_list",
  /*   40 */ "block",
  /*   41 */ "block_body",
  /*   42 */ "any",
  /*   43 */ "selector_list",
  /*   44 */ "declaration_list",
  /*   45 */ "any_list_1",
  /*   46 */ "selector",
  /*   47 */ "simple_selector",
  /*   48 */ "css_combinator",
  /*   49 */ "element_name",
  /*   50 */ "detail_list",
  /*   51 */ "detail",
  /*   52 */ "declaration",
  /*   53 */ "property",
  /*   54 */ "value",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "at_rule ::= ATKEYWORD ws any_list SEMI ws",
 /*   1 */ "ruleset ::= selector_list LBRACE ws declaration_list RBRACE ws",
 /*   2 */ "ruleset ::= LBRACE declaration_list RBRACE",
 /*   3 */ "ruleset ::= any_list_1 LBRACE declaration_list RBRACE",
 /*   4 */ "selector_list ::= selector ws",
 /*   5 */ "selector_list ::= selector_list COMMA ws selector ws",
 /*   6 */ "selector ::= simple_selector",
 /*   7 */ "selector ::= selector css_combinator simple_selector",
 /*   8 */ "css_combinator ::= ws PLUS ws",
 /*   9 */ "css_combinator ::= ws GT ws",
 /*  10 */ "css_combinator ::= ws_1",
 /*  11 */ "simple_selector ::= element_name detail_list",
 /*  12 */ "simple_selector ::= element_name",
 /*  13 */ "simple_selector ::= detail_list",
 /*  14 */ "element_name ::= IDENT",
 /*  15 */ "element_name ::= ASTERISK",
 /*  16 */ "detail_list ::= detail",
 /*  17 */ "detail_list ::= detail detail_list",
 /*  18 */ "detail ::= HASH",
 /*  19 */ "detail ::= DOT IDENT",
 /*  20 */ "detail ::= LBRAC ws IDENT ws RBRAC",
 /*  21 */ "detail ::= LBRAC ws IDENT ws EQUALS ws IDENT ws RBRAC",
 /*  22 */ "detail ::= LBRAC ws IDENT ws EQUALS ws STRING ws RBRAC",
 /*  23 */ "detail ::= LBRAC ws IDENT ws INCLUDES ws IDENT ws RBRAC",
 /*  24 */ "detail ::= LBRAC ws IDENT ws INCLUDES ws STRING ws RBRAC",
 /*  25 */ "detail ::= LBRAC ws IDENT ws DASHMATCH ws IDENT ws RBRAC",
 /*  26 */ "detail ::= LBRAC ws IDENT ws DASHMATCH ws STRING ws RBRAC",
 /*  27 */ "detail ::= LBRAC ws IDENT ws PREFIX ws IDENT ws RBRAC",
 /*  28 */ "detail ::= LBRAC ws IDENT ws PREFIX ws STRING ws RBRAC",
 /*  29 */ "detail ::= LBRAC ws IDENT ws SUFFIX ws IDENT ws RBRAC",
 /*  30 */ "detail ::= LBRAC ws IDENT ws SUFFIX ws STRING ws RBRAC",
 /*  31 */ "detail ::= LBRAC ws IDENT ws SUBSTR ws IDENT ws RBRAC",
 /*  32 */ "detail ::= LBRAC ws IDENT ws SUBSTR ws STRING ws RBRAC",
 /*  33 */ "detail ::= COLON IDENT",
 /*  34 */ "detail ::= COLON FUNCTION ws IDENT ws RPAREN",
 /*  35 */ "detail ::= COLON FUNCTION ws RPAREN",
 /*  36 */ "declaration_list ::=",
 /*  37 */ "declaration_list ::= declaration",
 /*  38 */ "declaration_list ::= declaration_list SEMI",
 /*  39 */ "declaration_list ::= declaration SEMI ws declaration_list",
 /*  40 */ "declaration ::= property ws COLON ws value ws",
 /*  41 */ "declaration ::= any_list_1",
 /*  42 */ "property ::= IDENT",
 /*  43 */ "value ::= any ws",
 /*  44 */ "value ::= any ws value",
 /*  45 */ "value ::= value ws block",
 /*  46 */ "value ::= value ws ATKEYWORD ws",
 /*  47 */ "any_list ::=",
 /*  48 */ "any_list ::= any ws any_list",
 /*  49 */ "any_list_1 ::= any ws any_list",
 /*  50 */ "any ::= IDENT",
 /*  51 */ "any ::= NUMBER",
 /*  52 */ "any ::= PERCENTAGE",
 /*  53 */ "any ::= DIMENSION",
 /*  54 */ "any ::= STRING",
 /*  55 */ "any ::= DELIM",
 /*  56 */ "any ::= URI",
 /*  57 */ "any ::= HASH",
 /*  58 */ "any ::= UNICODE_RANGE",
 /*  59 */ "any ::= INCLUDES",
 /*  60 */ "any ::= FUNCTION ws any_list RPAREN",
 /*  61 */ "any ::= DASHMATCH",
 /*  62 */ "any ::= PREFIX",
 /*  63 */ "any ::= SUFFIX",
 /*  64 */ "any ::= SUBSTR",
 /*  65 */ "any ::= COLON",
 /*  66 */ "any ::= COMMA",
 /*  67 */ "any ::= DOT",
 /*  68 */ "any ::= PLUS",
 /*  69 */ "any ::= GT",
 /*  70 */ "any ::= LPAREN ws any_list RPAREN",
 /*  71 */ "any ::= LBRAC ws any_list RBRAC",
 /*  72 */ "any ::= ASTERISK",
 /*  73 */ "stylesheet ::= ws statement_list",
 /*  74 */ "ws ::=",
 /*  75 */ "ws ::= ws_1",
 /*  76 */ "ws_1 ::= S",
 /*  77 */ "ws_1 ::= ws_1 S",
 /*  78 */ "statement_list ::=",
 /*  79 */ "statement_list ::= statement_list statement",
 /*  80 */ "statement ::= ws_1",
 /*  81 */ "statement ::= ruleset",
 /*  82 */ "statement ::= at_rule",
 /*  83 */ "at_rule ::= ATKEYWORD ws any_list block",
 /*  84 */ "block ::= LBRACE ws block_body RBRACE ws",
 /*  85 */ "block_body ::=",
 /*  86 */ "block_body ::= block_body any ws",
 /*  87 */ "block_body ::= block_body block",
 /*  88 */ "block_body ::= block_body ATKEYWORD ws",
 /*  89 */ "block_body ::= block_body SEMI ws",
 /*  90 */ "declaration ::= DELIM property ws COLON ws value ws",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to css_parser_Alloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void css_parser_Init(void *yypRawParser css_parser_CTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  css_parser_CTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef css_parser__ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to css_parser_ and css_parser_Free.
*/
void *css_parser_Alloc(void *(*mallocProc)(YYMALLOCARGTYPE) css_parser_CTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    css_parser_CTX_STORE
    css_parser_Init(yypParser css_parser_CTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* css_parser__ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  css_parser_ARG_FETCH
  css_parser_CTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
    case 39: /* any_list */
    case 42: /* any */
    case 44: /* declaration_list */
    case 45: /* any_list_1 */
    case 52: /* declaration */
    case 54: /* value */
{
#line 432 "parser.y"
 css_free_node((yypminor->yy50)); 
#line 765 "parser.c"
}
      break;
    case 43: /* selector_list */
    case 46: /* selector */
    case 47: /* simple_selector */
    case 50: /* detail_list */
    case 51: /* detail */
{
#line 424 "parser.y"
 css_free_selector((yypminor->yy17)); 
#line 776 "parser.c"
}
      break;
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void css_parser_Finalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef css_parser__ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void css_parser_Free(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  css_parser_Finalize(p);
  (*freeProc)(p);
}
#endif /* css_parser__ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int css_parser_StackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int css_parser_Coverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   css_parser_ARG_FETCH
   css_parser_CTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   css_parser_ARG_STORE /* Suppress warning about unused %extra_argument var */
   css_parser_CTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  css_parser_TOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    38,  /* (0) at_rule ::= ATKEYWORD ws any_list SEMI ws */
    37,  /* (1) ruleset ::= selector_list LBRACE ws declaration_list RBRACE ws */
    37,  /* (2) ruleset ::= LBRACE declaration_list RBRACE */
    37,  /* (3) ruleset ::= any_list_1 LBRACE declaration_list RBRACE */
    43,  /* (4) selector_list ::= selector ws */
    43,  /* (5) selector_list ::= selector_list COMMA ws selector ws */
    46,  /* (6) selector ::= simple_selector */
    46,  /* (7) selector ::= selector css_combinator simple_selector */
    48,  /* (8) css_combinator ::= ws PLUS ws */
    48,  /* (9) css_combinator ::= ws GT ws */
    48,  /* (10) css_combinator ::= ws_1 */
    47,  /* (11) simple_selector ::= element_name detail_list */
    47,  /* (12) simple_selector ::= element_name */
    47,  /* (13) simple_selector ::= detail_list */
    49,  /* (14) element_name ::= IDENT */
    49,  /* (15) element_name ::= ASTERISK */
    50,  /* (16) detail_list ::= detail */
    50,  /* (17) detail_list ::= detail detail_list */
    51,  /* (18) detail ::= HASH */
    51,  /* (19) detail ::= DOT IDENT */
    51,  /* (20) detail ::= LBRAC ws IDENT ws RBRAC */
    51,  /* (21) detail ::= LBRAC ws IDENT ws EQUALS ws IDENT ws RBRAC */
    51,  /* (22) detail ::= LBRAC ws IDENT ws EQUALS ws STRING ws RBRAC */
    51,  /* (23) detail ::= LBRAC ws IDENT ws INCLUDES ws IDENT ws RBRAC */
    51,  /* (24) detail ::= LBRAC ws IDENT ws INCLUDES ws STRING ws RBRAC */
    51,  /* (25) detail ::= LBRAC ws IDENT ws DASHMATCH ws IDENT ws RBRAC */
    51,  /* (26) detail ::= LBRAC ws IDENT ws DASHMATCH ws STRING ws RBRAC */
    51,  /* (27) detail ::= LBRAC ws IDENT ws PREFIX ws IDENT ws RBRAC */
    51,  /* (28) detail ::= LBRAC ws IDENT ws PREFIX ws STRING ws RBRAC */
    51,  /* (29) detail ::= LBRAC ws IDENT ws SUFFIX ws IDENT ws RBRAC */
    51,  /* (30) detail ::= LBRAC ws IDENT ws SUFFIX ws STRING ws RBRAC */
    51,  /* (31) detail ::= LBRAC ws IDENT ws SUBSTR ws IDENT ws RBRAC */
    51,  /* (32) detail ::= LBRAC ws IDENT ws SUBSTR ws STRING ws RBRAC */
    51,  /* (33) detail ::= COLON IDENT */
    51,  /* (34) detail ::= COLON FUNCTION ws IDENT ws RPAREN */
    51,  /* (35) detail ::= COLON FUNCTION ws RPAREN */
    44,  /* (36) declaration_list ::= */
    44,  /* (37) declaration_list ::= declaration */
    44,  /* (38) declaration_list ::= declaration_list SEMI */
    44,  /* (39) declaration_list ::= declaration SEMI ws declaration_list */
    52,  /* (40) declaration ::= property ws COLON ws value ws */
    52,  /* (41) declaration ::= any_list_1 */
    53,  /* (42) property ::= IDENT */
    54,  /* (43) value ::= any ws */
    54,  /* (44) value ::= any ws value */
    54,  /* (45) value ::= value ws block */
    54,  /* (46) value ::= value ws ATKEYWORD ws */
    39,  /* (47) any_list ::= */
    39,  /* (48) any_list ::= any ws any_list */
    45,  /* (49) any_list_1 ::= any ws any_list */
    42,  /* (50) any ::= IDENT */
    42,  /* (51) any ::= NUMBER */
    42,  /* (52) any ::= PERCENTAGE */
    42,  /* (53) any ::= DIMENSION */
    42,  /* (54) any ::= STRING */
    42,  /* (55) any ::= DELIM */
    42,  /* (56) any ::= URI */
    42,  /* (57) any ::= HASH */
    42,  /* (58) any ::= UNICODE_RANGE */
    42,  /* (59) any ::= INCLUDES */
    42,  /* (60) any ::= FUNCTION ws any_list RPAREN */
    42,  /* (61) any ::= DASHMATCH */
    42,  /* (62) any ::= PREFIX */
    42,  /* (63) any ::= SUFFIX */
    42,  /* (64) any ::= SUBSTR */
    42,  /* (65) any ::= COLON */
    42,  /* (66) any ::= COMMA */
    42,  /* (67) any ::= DOT */
    42,  /* (68) any ::= PLUS */
    42,  /* (69) any ::= GT */
    42,  /* (70) any ::= LPAREN ws any_list RPAREN */
    42,  /* (71) any ::= LBRAC ws any_list RBRAC */
    42,  /* (72) any ::= ASTERISK */
    32,  /* (73) stylesheet ::= ws statement_list */
    33,  /* (74) ws ::= */
    33,  /* (75) ws ::= ws_1 */
    35,  /* (76) ws_1 ::= S */
    35,  /* (77) ws_1 ::= ws_1 S */
    34,  /* (78) statement_list ::= */
    34,  /* (79) statement_list ::= statement_list statement */
    36,  /* (80) statement ::= ws_1 */
    36,  /* (81) statement ::= ruleset */
    36,  /* (82) statement ::= at_rule */
    38,  /* (83) at_rule ::= ATKEYWORD ws any_list block */
    40,  /* (84) block ::= LBRACE ws block_body RBRACE ws */
    41,  /* (85) block_body ::= */
    41,  /* (86) block_body ::= block_body any ws */
    41,  /* (87) block_body ::= block_body block */
    41,  /* (88) block_body ::= block_body ATKEYWORD ws */
    41,  /* (89) block_body ::= block_body SEMI ws */
    52,  /* (90) declaration ::= DELIM property ws COLON ws value ws */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -5,  /* (0) at_rule ::= ATKEYWORD ws any_list SEMI ws */
   -6,  /* (1) ruleset ::= selector_list LBRACE ws declaration_list RBRACE ws */
   -3,  /* (2) ruleset ::= LBRACE declaration_list RBRACE */
   -4,  /* (3) ruleset ::= any_list_1 LBRACE declaration_list RBRACE */
   -2,  /* (4) selector_list ::= selector ws */
   -5,  /* (5) selector_list ::= selector_list COMMA ws selector ws */
   -1,  /* (6) selector ::= simple_selector */
   -3,  /* (7) selector ::= selector css_combinator simple_selector */
   -3,  /* (8) css_combinator ::= ws PLUS ws */
   -3,  /* (9) css_combinator ::= ws GT ws */
   -1,  /* (10) css_combinator ::= ws_1 */
   -2,  /* (11) simple_selector ::= element_name detail_list */
   -1,  /* (12) simple_selector ::= element_name */
   -1,  /* (13) simple_selector ::= detail_list */
   -1,  /* (14) element_name ::= IDENT */
   -1,  /* (15) element_name ::= ASTERISK */
   -1,  /* (16) detail_list ::= detail */
   -2,  /* (17) detail_list ::= detail detail_list */
   -1,  /* (18) detail ::= HASH */
   -2,  /* (19) detail ::= DOT IDENT */
   -5,  /* (20) detail ::= LBRAC ws IDENT ws RBRAC */
   -9,  /* (21) detail ::= LBRAC ws IDENT ws EQUALS ws IDENT ws RBRAC */
   -9,  /* (22) detail ::= LBRAC ws IDENT ws EQUALS ws STRING ws RBRAC */
   -9,  /* (23) detail ::= LBRAC ws IDENT ws INCLUDES ws IDENT ws RBRAC */
   -9,  /* (24) detail ::= LBRAC ws IDENT ws INCLUDES ws STRING ws RBRAC */
   -9,  /* (25) detail ::= LBRAC ws IDENT ws DASHMATCH ws IDENT ws RBRAC */
   -9,  /* (26) detail ::= LBRAC ws IDENT ws DASHMATCH ws STRING ws RBRAC */
   -9,  /* (27) detail ::= LBRAC ws IDENT ws PREFIX ws IDENT ws RBRAC */
   -9,  /* (28) detail ::= LBRAC ws IDENT ws PREFIX ws STRING ws RBRAC */
   -9,  /* (29) detail ::= LBRAC ws IDENT ws SUFFIX ws IDENT ws RBRAC */
   -9,  /* (30) detail ::= LBRAC ws IDENT ws SUFFIX ws STRING ws RBRAC */
   -9,  /* (31) detail ::= LBRAC ws IDENT ws SUBSTR ws IDENT ws RBRAC */
   -9,  /* (32) detail ::= LBRAC ws IDENT ws SUBSTR ws STRING ws RBRAC */
   -2,  /* (33) detail ::= COLON IDENT */
   -6,  /* (34) detail ::= COLON FUNCTION ws IDENT ws RPAREN */
   -4,  /* (35) detail ::= COLON FUNCTION ws RPAREN */
    0,  /* (36) declaration_list ::= */
   -1,  /* (37) declaration_list ::= declaration */
   -2,  /* (38) declaration_list ::= declaration_list SEMI */
   -4,  /* (39) declaration_list ::= declaration SEMI ws declaration_list */
   -6,  /* (40) declaration ::= property ws COLON ws value ws */
   -1,  /* (41) declaration ::= any_list_1 */
   -1,  /* (42) property ::= IDENT */
   -2,  /* (43) value ::= any ws */
   -3,  /* (44) value ::= any ws value */
   -3,  /* (45) value ::= value ws block */
   -4,  /* (46) value ::= value ws ATKEYWORD ws */
    0,  /* (47) any_list ::= */
   -3,  /* (48) any_list ::= any ws any_list */
   -3,  /* (49) any_list_1 ::= any ws any_list */
   -1,  /* (50) any ::= IDENT */
   -1,  /* (51) any ::= NUMBER */
   -1,  /* (52) any ::= PERCENTAGE */
   -1,  /* (53) any ::= DIMENSION */
   -1,  /* (54) any ::= STRING */
   -1,  /* (55) any ::= DELIM */
   -1,  /* (56) any ::= URI */
   -1,  /* (57) any ::= HASH */
   -1,  /* (58) any ::= UNICODE_RANGE */
   -1,  /* (59) any ::= INCLUDES */
   -4,  /* (60) any ::= FUNCTION ws any_list RPAREN */
   -1,  /* (61) any ::= DASHMATCH */
   -1,  /* (62) any ::= PREFIX */
   -1,  /* (63) any ::= SUFFIX */
   -1,  /* (64) any ::= SUBSTR */
   -1,  /* (65) any ::= COLON */
   -1,  /* (66) any ::= COMMA */
   -1,  /* (67) any ::= DOT */
   -1,  /* (68) any ::= PLUS */
   -1,  /* (69) any ::= GT */
   -4,  /* (70) any ::= LPAREN ws any_list RPAREN */
   -4,  /* (71) any ::= LBRAC ws any_list RBRAC */
   -1,  /* (72) any ::= ASTERISK */
   -2,  /* (73) stylesheet ::= ws statement_list */
    0,  /* (74) ws ::= */
   -1,  /* (75) ws ::= ws_1 */
   -1,  /* (76) ws_1 ::= S */
   -2,  /* (77) ws_1 ::= ws_1 S */
    0,  /* (78) statement_list ::= */
   -2,  /* (79) statement_list ::= statement_list statement */
   -1,  /* (80) statement ::= ws_1 */
   -1,  /* (81) statement ::= ruleset */
   -1,  /* (82) statement ::= at_rule */
   -4,  /* (83) at_rule ::= ATKEYWORD ws any_list block */
   -5,  /* (84) block ::= LBRACE ws block_body RBRACE ws */
    0,  /* (85) block_body ::= */
   -3,  /* (86) block_body ::= block_body any ws */
   -2,  /* (87) block_body ::= block_body block */
   -3,  /* (88) block_body ::= block_body ATKEYWORD ws */
   -3,  /* (89) block_body ::= block_body SEMI ws */
   -7,  /* (90) declaration ::= DELIM property ws COLON ws value ws */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  css_parser_TOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  css_parser_CTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  css_parser_ARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* at_rule ::= ATKEYWORD ws any_list SEMI ws */
#line 49 "parser.y"
{ if ((yymsp[-4].minor.yy0.length == 7) && (strncasecmp(yymsp[-4].minor.yy0.text, "@import", 7) == 0)
				&& yymsp[-2].minor.yy50 && !param->had_ruleset)
			css_atimport(param->stylesheet, yymsp[-2].minor.yy50);
		css_free_node(yymsp[-2].minor.yy50); }
#line 1299 "parser.c"
        break;
      case 1: /* ruleset ::= selector_list LBRACE ws declaration_list RBRACE ws */
#line 62 "parser.y"
{ if (yymsp[-5].minor.yy17 && yymsp[-2].minor.yy50) {
			/*param->had_ruleset = true;*/
			css_add_ruleset(param->stylesheet, yymsp[-5].minor.yy17, yymsp[-2].minor.yy50);
		}
		else
			css_free_selector(yymsp[-5].minor.yy17);
		css_free_node(yymsp[-2].minor.yy50); }
#line 1310 "parser.c"
        break;
      case 2: /* ruleset ::= LBRACE declaration_list RBRACE */
#line 72 "parser.y"
{ if (param->ruleset_only) param->declaration = yymsp[-1].minor.yy50;
		  else css_free_node(yymsp[-1].minor.yy50); }
#line 1316 "parser.c"
        break;
      case 3: /* ruleset ::= any_list_1 LBRACE declaration_list RBRACE */
#line 75 "parser.y"
{ css_free_node(yymsp[-3].minor.yy50); css_free_node(yymsp[-1].minor.yy50); }
#line 1321 "parser.c"
        break;
      case 4: /* selector_list ::= selector ws */
#line 78 "parser.y"
{ yylhsminor.yy17 = yymsp[-1].minor.yy17; }
#line 1326 "parser.c"
  yymsp[-1].minor.yy17 = yylhsminor.yy17;
        break;
      case 5: /* selector_list ::= selector_list COMMA ws selector ws */
#line 80 "parser.y"
{ if (yymsp[-4].minor.yy17 && yymsp[-1].minor.yy17) {
			yymsp[-1].minor.yy17->next = yymsp[-4].minor.yy17;
			yylhsminor.yy17 = yymsp[-1].minor.yy17;
		} else {
			css_free_selector(yymsp[-4].minor.yy17);
			css_free_selector(yymsp[-1].minor.yy17);
			yylhsminor.yy17 = 0;
		} }
#line 1339 "parser.c"
  yymsp[-4].minor.yy17 = yylhsminor.yy17;
        break;
      case 6: /* selector ::= simple_selector */
      case 16: /* detail_list ::= detail */ yytestcase(yyruleno==16);
#line 90 "parser.y"
{ yylhsminor.yy17 = yymsp[0].minor.yy17; }
#line 1346 "parser.c"
  yymsp[0].minor.yy17 = yylhsminor.yy17;
        break;
      case 7: /* selector ::= selector css_combinator simple_selector */
#line 92 "parser.y"
{ if (yymsp[-2].minor.yy17 && yymsp[0].minor.yy17) {
			yymsp[0].minor.yy17->combiner = yymsp[-2].minor.yy17;
			yymsp[0].minor.yy17->comb = yymsp[-1].minor.yy57;
			yymsp[0].minor.yy17->specificity += yymsp[-2].minor.yy17->specificity;
			yylhsminor.yy17 = yymsp[0].minor.yy17;
		} else {
			css_free_selector(yymsp[-2].minor.yy17);
			css_free_selector(yymsp[0].minor.yy17);
			yylhsminor.yy17 = 0;
		} }
#line 1361 "parser.c"
  yymsp[-2].minor.yy17 = yylhsminor.yy17;
        break;
      case 8: /* css_combinator ::= ws PLUS ws */
#line 104 "parser.y"
{ yymsp[-2].minor.yy57 = CSS_COMB_PRECEDED; }
#line 1367 "parser.c"
        break;
      case 9: /* css_combinator ::= ws GT ws */
#line 106 "parser.y"
{ yymsp[-2].minor.yy57 = CSS_COMB_PARENT; }
#line 1372 "parser.c"
        break;
      case 10: /* css_combinator ::= ws_1 */
#line 108 "parser.y"
{ yymsp[0].minor.yy57 = CSS_COMB_ANCESTOR; }
#line 1377 "parser.c"
        break;
      case 11: /* simple_selector ::= element_name detail_list */
#line 111 "parser.y"
{ if (yymsp[0].minor.yy17 && (yylhsminor.yy17 = css_new_selector(CSS_SELECTOR_ELEMENT,
				yymsp[-1].minor.yy0.text, yymsp[-1].minor.yy0.length))) {
			yylhsminor.yy17->detail = yymsp[0].minor.yy17;
			yylhsminor.yy17->specificity = 1 + yymsp[0].minor.yy17->specificity;
		} else {
			param->memory_error = true;
			css_free_selector(yymsp[0].minor.yy17);
			yylhsminor.yy17 = 0;
		} }
#line 1390 "parser.c"
  yymsp[-1].minor.yy17 = yylhsminor.yy17;
        break;
      case 12: /* simple_selector ::= element_name */
#line 121 "parser.y"
{ if ((yylhsminor.yy17 = css_new_selector(CSS_SELECTOR_ELEMENT,
				yymsp[0].minor.yy0.text, yymsp[0].minor.yy0.length)))
			yylhsminor.yy17->specificity = CSS_SPECIFICITY_ELEMENT;
		else
			param->memory_error = true;
		}
#line 1401 "parser.c"
  yymsp[0].minor.yy17 = yylhsminor.yy17;
        break;
      case 13: /* simple_selector ::= detail_list */
#line 128 "parser.y"
{ if (yymsp[0].minor.yy17 && (yylhsminor.yy17 = css_new_selector(CSS_SELECTOR_ELEMENT, 0, 0))) {
			yylhsminor.yy17->detail = yymsp[0].minor.yy17;
			yylhsminor.yy17->specificity = yymsp[0].minor.yy17->specificity;
		} else {
			param->memory_error = true;
			css_free_selector(yymsp[0].minor.yy17);
			yylhsminor.yy17 = 0;
                } }
#line 1414 "parser.c"
  yymsp[0].minor.yy17 = yylhsminor.yy17;
        break;
      case 14: /* element_name ::= IDENT */
      case 42: /* property ::= IDENT */ yytestcase(yyruleno==42);
#line 138 "parser.y"
{ yylhsminor.yy0 = yymsp[0].minor.yy0; }
#line 1421 "parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 15: /* element_name ::= ASTERISK */
#line 140 "parser.y"
{ yymsp[0].minor.yy0.text = 0; }
#line 1427 "parser.c"
        break;
      case 17: /* detail_list ::= detail detail_list */
#line 145 "parser.y"
{ if (yymsp[-1].minor.yy17 && yymsp[0].minor.yy17) {
			yymsp[-1].minor.yy17->specificity += yymsp[0].minor.yy17->specificity;
			yymsp[-1].minor.yy17->next = yymsp[0].minor.yy17;
			yylhsminor.yy17 = yymsp[-1].minor.yy17;
		} else {
			css_free_selector(yymsp[-1].minor.yy17);
			css_free_selector(yymsp[0].minor.yy17);
			yylhsminor.yy17 = 0;
		} }
#line 1440 "parser.c"
  yymsp[-1].minor.yy17 = yylhsminor.yy17;
        break;
      case 18: /* detail ::= HASH */
#line 156 "parser.y"
{ yylhsminor.yy17 = css_new_selector(CSS_SELECTOR_ID, yymsp[0].minor.yy0.text+1, yymsp[0].minor.yy0.length-1);
		if (yylhsminor.yy17) yylhsminor.yy17->specificity = CSS_SPECIFICITY_ID;
		else param->memory_error = true; }
#line 1448 "parser.c"
  yymsp[0].minor.yy17 = yylhsminor.yy17;
        break;
      case 19: /* detail ::= DOT IDENT */
#line 160 "parser.y"
{ yymsp[-1].minor.yy17 = css_new_selector(CSS_SELECTOR_CLASS, yymsp[0].minor.yy0.text, yymsp[0].minor.yy0.length);
		if (yymsp[-1].minor.yy17) yymsp[-1].minor.yy17->specificity = CSS_SPECIFICITY_CLASS;
		else param->memory_error = true; }
#line 1456 "parser.c"
        break;
      case 20: /* detail ::= LBRAC ws IDENT ws RBRAC */
#line 164 "parser.y"
{ yymsp[-4].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB, yymsp[-2].minor.yy0.text, yymsp[-2].minor.yy0.length);
		if (yymsp[-4].minor.yy17) yymsp[-4].minor.yy17->specificity = CSS_SPECIFICITY_ATTR;
		else param->memory_error = true; }
#line 1463 "parser.c"
        break;
      case 21: /* detail ::= LBRAC ws IDENT ws EQUALS ws IDENT ws RBRAC */
#line 168 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_EQ, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1471 "parser.c"
        break;
      case 22: /* detail ::= LBRAC ws IDENT ws EQUALS ws STRING ws RBRAC */
#line 173 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_EQ, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text + 1; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length - 2;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1479 "parser.c"
        break;
      case 23: /* detail ::= LBRAC ws IDENT ws INCLUDES ws IDENT ws RBRAC */
#line 178 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_INC, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1487 "parser.c"
        break;
      case 24: /* detail ::= LBRAC ws IDENT ws INCLUDES ws STRING ws RBRAC */
#line 183 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_INC, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text + 1; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length - 2;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1495 "parser.c"
        break;
      case 25: /* detail ::= LBRAC ws IDENT ws DASHMATCH ws IDENT ws RBRAC */
#line 188 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_DM, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1503 "parser.c"
        break;
      case 26: /* detail ::= LBRAC ws IDENT ws DASHMATCH ws STRING ws RBRAC */
#line 193 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_DM, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text + 1; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length - 2;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1511 "parser.c"
        break;
      case 27: /* detail ::= LBRAC ws IDENT ws PREFIX ws IDENT ws RBRAC */
#line 198 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_PRE, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1519 "parser.c"
        break;
      case 28: /* detail ::= LBRAC ws IDENT ws PREFIX ws STRING ws RBRAC */
#line 203 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_PRE, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text + 1; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length - 2;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1527 "parser.c"
        break;
      case 29: /* detail ::= LBRAC ws IDENT ws SUFFIX ws IDENT ws RBRAC */
#line 208 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_SUF, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1535 "parser.c"
        break;
      case 30: /* detail ::= LBRAC ws IDENT ws SUFFIX ws STRING ws RBRAC */
#line 213 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_SUF, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text + 1; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length - 2;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1543 "parser.c"
        break;
      case 31: /* detail ::= LBRAC ws IDENT ws SUBSTR ws IDENT ws RBRAC */
#line 218 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_SUB, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1551 "parser.c"
        break;
      case 32: /* detail ::= LBRAC ws IDENT ws SUBSTR ws STRING ws RBRAC */
#line 223 "parser.y"
{ yymsp[-8].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB_SUB, yymsp[-6].minor.yy0.text, yymsp[-6].minor.yy0.length);
		if (yymsp[-8].minor.yy17) { yymsp[-8].minor.yy17->data2 = yymsp[-2].minor.yy0.text + 1; yymsp[-8].minor.yy17->data2_length = yymsp[-2].minor.yy0.length - 2;
			yymsp[-8].minor.yy17->specificity = CSS_SPECIFICITY_ATTR; }
		else param->memory_error = true; }
#line 1559 "parser.c"
        break;
      case 33: /* detail ::= COLON IDENT */
#line 228 "parser.y"
{ if (yymsp[0].minor.yy0.length == 4 && strncasecmp(yymsp[0].minor.yy0.text, "link", 4) == 0) {
			yymsp[-1].minor.yy17 = css_new_selector(CSS_SELECTOR_ATTRIB, "href", 4);
			if (yymsp[-1].minor.yy17) yymsp[-1].minor.yy17->specificity = CSS_SPECIFICITY_ATTR;
			else param->memory_error = true;
		} else {
			yymsp[-1].minor.yy17 = css_new_selector(CSS_SELECTOR_PSEUDO, yymsp[0].minor.yy0.text, yymsp[0].minor.yy0.length);
			if (yymsp[-1].minor.yy17) yymsp[-1].minor.yy17->specificity = CSS_SPECIFICITY_ATTR;
			else param->memory_error = true;
		} }
#line 1572 "parser.c"
        break;
      case 34: /* detail ::= COLON FUNCTION ws IDENT ws RPAREN */
#line 238 "parser.y"
{ yymsp[-5].minor.yy17 = css_new_selector(CSS_SELECTOR_PSEUDO, yymsp[-4].minor.yy0.text, yymsp[-4].minor.yy0.length);
		if (yymsp[-5].minor.yy17) yymsp[-5].minor.yy17->specificity = CSS_SPECIFICITY_ATTR;
		else param->memory_error = true; }
#line 1579 "parser.c"
        break;
      case 35: /* detail ::= COLON FUNCTION ws RPAREN */
#line 242 "parser.y"
{ yymsp[-3].minor.yy17 = css_new_selector(CSS_SELECTOR_PSEUDO, yymsp[-2].minor.yy0.text, yymsp[-2].minor.yy0.length);
		if (yymsp[-3].minor.yy17) yymsp[-3].minor.yy17->specificity = CSS_SPECIFICITY_ATTR;
		else param->memory_error = true; }
#line 1586 "parser.c"
        break;
      case 36: /* declaration_list ::= */
      case 47: /* any_list ::= */ yytestcase(yyruleno==47);
#line 247 "parser.y"
{ yymsp[1].minor.yy50 = 0; }
#line 1592 "parser.c"
        break;
      case 37: /* declaration_list ::= declaration */
#line 249 "parser.y"
{ yylhsminor.yy50 = yymsp[0].minor.yy50; }
#line 1597 "parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 38: /* declaration_list ::= declaration_list SEMI */
      case 43: /* value ::= any ws */ yytestcase(yyruleno==43);
#line 251 "parser.y"
{ yylhsminor.yy50 = yymsp[-1].minor.yy50; }
#line 1604 "parser.c"
  yymsp[-1].minor.yy50 = yylhsminor.yy50;
        break;
      case 39: /* declaration_list ::= declaration SEMI ws declaration_list */
#line 253 "parser.y"
{ if (yymsp[-3].minor.yy50) { yymsp[-3].minor.yy50->next = yymsp[0].minor.yy50; yylhsminor.yy50 = yymsp[-3].minor.yy50; } else { yylhsminor.yy50 = yymsp[0].minor.yy50; } }
#line 1610 "parser.c"
  yymsp[-3].minor.yy50 = yylhsminor.yy50;
        break;
      case 40: /* declaration ::= property ws COLON ws value ws */
#line 259 "parser.y"
{ if (yymsp[-1].minor.yy50 && (yylhsminor.yy50 = css_new_node(param->stylesheet,
		                CSS_NODE_DECLARATION,
				yymsp[-5].minor.yy0.text, yymsp[-5].minor.yy0.length))) {
			yylhsminor.yy50->value = yymsp[-1].minor.yy50;
		} else {
			param->memory_error = true;
			css_free_node(yymsp[-1].minor.yy50);
			yylhsminor.yy50 = 0;
		} }
#line 1624 "parser.c"
  yymsp[-5].minor.yy50 = yylhsminor.yy50;
        break;
      case 41: /* declaration ::= any_list_1 */
#line 269 "parser.y"
{ yylhsminor.yy50 = 0; css_free_node(yymsp[0].minor.yy50); }
#line 1630 "parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 44: /* value ::= any ws value */
#line 277 "parser.y"
{ if (yymsp[-2].minor.yy50 && yymsp[0].minor.yy50) { yymsp[-2].minor.yy50->next = yymsp[0].minor.yy50; yylhsminor.yy50 = yymsp[-2].minor.yy50; }
		else { css_free_node(yymsp[-2].minor.yy50); css_free_node(yymsp[0].minor.yy50); yylhsminor.yy50 = 0; } }
#line 1637 "parser.c"
  yymsp[-2].minor.yy50 = yylhsminor.yy50;
        break;
      case 45: /* value ::= value ws block */
#line 280 "parser.y"
{ yylhsminor.yy50 = yymsp[-2].minor.yy50; }
#line 1643 "parser.c"
  yymsp[-2].minor.yy50 = yylhsminor.yy50;
        break;
      case 46: /* value ::= value ws ATKEYWORD ws */
#line 282 "parser.y"
{ yylhsminor.yy50 = yymsp[-3].minor.yy50; }
#line 1649 "parser.c"
  yymsp[-3].minor.yy50 = yylhsminor.yy50;
        break;
      case 48: /* any_list ::= any ws any_list */
      case 49: /* any_list_1 ::= any ws any_list */ yytestcase(yyruleno==49);
#line 288 "parser.y"
{ if (yymsp[-2].minor.yy50) { yymsp[-2].minor.yy50->next = yymsp[0].minor.yy50; yylhsminor.yy50 = yymsp[-2].minor.yy50; }
		else { css_free_node(yymsp[-2].minor.yy50); css_free_node(yymsp[0].minor.yy50); yylhsminor.yy50 = 0; } }
#line 1657 "parser.c"
  yymsp[-2].minor.yy50 = yylhsminor.yy50;
        break;
      case 50: /* any ::= IDENT */
#line 294 "parser.y"
{ yylhsminor.yy50 = css_new_node(param->stylesheet, CSS_NODE_IDENT,
		                   yymsp[0].minor.yy0.text, yymsp[0].minor.yy0.length);
		if (!yylhsminor.yy50) param->memory_error = true; }
#line 1665 "parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 51: /* any ::= NUMBER */
#line 298 "parser.y"
{ yylhsminor.yy50 = css_new_node(param->stylesheet, CSS_NODE_NUMBER,
		                   yymsp[0].minor.yy0.text, yymsp[0].minor.yy0.length);
		if (!yylhsminor.yy50) param->memory_error = true; }
#line 1673 "parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 52: /* any ::= PERCENTAGE */
#line 302 "parser.y"
{ yylhsminor.yy50 = css_new_node(param->stylesheet, CSS_NODE_PERCENTAGE,
		                   yymsp[0].minor.yy0.text, yymsp[0].minor.yy0.length);
		if (!yylhsminor.yy50) param->memory_error = true; }
#line 1681 "parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 53: /* any ::= DIMENSION */
#line 306 "parser.y"
{ yylhsminor.yy50 = css_new_node(param->stylesheet, CSS_NODE_DIMENSION,
		                   yymsp[0].minor.yy0.text, yymsp[0].minor.yy0.length);
		if (!yylhsminor.yy50) param->memory_error = true; }
#line 1689 "parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 54: /* any ::= STRING */
#line 310 "parser.y"
{ yylhsminor.yy50 = css_new_node(param->stylesheet, CSS_NODE_STRING,
		                   yymsp[0].minor.yy0.text + 1, yymsp[0].minor.yy0.length - 2);
		if (!yylhsminor.yy50) param->memory_error = true; }
#line 1697 "parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 55: /* any ::= DELIM */
      case 72: /* any ::= ASTERISK */ yytestcase(yyruleno==72);
#line 314 "parser.y"
{ yylhsminor.yy50 = css_new_node(param->stylesheet, CSS_NODE_DELIM,
		                   yymsp[0].minor.yy0.text, yymsp[0].minor.yy0.length);
		if (!yylhsminor.yy50) param->memory_error = true; }
#line 1706 "parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 56: /* any ::= URI */
#line 318 "parser.y"
{ yylhsminor.yy50 = css_new_node(param->stylesheet, CSS_NODE_URI,
		                   yymsp[0].minor.yy0.text, yymsp[0].minor.yy0.length);
		if (!yylhsminor.yy50) param->memory_error = true; }
#line 1714 "parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 57: /* any ::= HASH */
#line 322 "parser.y"
{ yylhsminor.yy50 = css_new_node(param->stylesheet, CSS_NODE_HASH,
		                   yymsp[0].minor.yy0.text, yymsp[0].minor.yy0.length);
		if (!yylhsminor.yy50) param->memory_error = true; }
#line 1722 "parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 58: /* any ::= UNICODE_RANGE */
#line 326 "parser.y"
{ yylhsminor.yy50 = css_new_node(param->stylesheet, CSS_NODE_UNICODE_RANGE,
		                   yymsp[0].minor.yy0.text, yymsp[0].minor.yy0.length);
		if (!yylhsminor.yy50) param->memory_error = true; }
#line 1730 "parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 59: /* any ::= INCLUDES */
#line 330 "parser.y"
{ yymsp[0].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_INCLUDES,
		                   0, 0);
		if (!yymsp[0].minor.yy50) param->memory_error = true; }
#line 1738 "parser.c"
        break;
      case 60: /* any ::= FUNCTION ws any_list RPAREN */
#line 334 "parser.y"
{ if ((yylhsminor.yy50 = css_new_node(param->stylesheet, CSS_NODE_FUNCTION,
		                        yymsp[-3].minor.yy0.text, yymsp[-3].minor.yy0.length)))
			yylhsminor.yy50->value = yymsp[-1].minor.yy50;
		else {
			param->memory_error = true;
			css_free_node(yymsp[-1].minor.yy50);
			yylhsminor.yy50 = 0;
		} }
#line 1750 "parser.c"
  yymsp[-3].minor.yy50 = yylhsminor.yy50;
        break;
      case 61: /* any ::= DASHMATCH */
#line 343 "parser.y"
{ yymsp[0].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_DASHMATCH,
		                   0, 0);
		if (!yymsp[0].minor.yy50) param->memory_error = true; }
#line 1758 "parser.c"
        break;
      case 62: /* any ::= PREFIX */
#line 347 "parser.y"
{ yymsp[0].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_PREFIX,
		                   0, 0);
		if (!yymsp[0].minor.yy50) param->memory_error = true; }
#line 1765 "parser.c"
        break;
      case 63: /* any ::= SUFFIX */
#line 351 "parser.y"
{ yymsp[0].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_SUFFIX,
		                   0, 0);
		if (!yymsp[0].minor.yy50) param->memory_error = true; }
#line 1772 "parser.c"
        break;
      case 64: /* any ::= SUBSTR */
#line 355 "parser.y"
{ yymsp[0].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_SUBSTR,
		                   0, 0);
		if (!yymsp[0].minor.yy50) param->memory_error = true; }
#line 1779 "parser.c"
        break;
      case 65: /* any ::= COLON */
#line 359 "parser.y"
{ yymsp[0].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_COLON, 0, 0);
		if (!yymsp[0].minor.yy50) param->memory_error = true; }
#line 1785 "parser.c"
        break;
      case 66: /* any ::= COMMA */
#line 362 "parser.y"
{ yymsp[0].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_COMMA, 0, 0);
		if (!yymsp[0].minor.yy50) param->memory_error = true; }
#line 1791 "parser.c"
        break;
      case 67: /* any ::= DOT */
#line 365 "parser.y"
{ yymsp[0].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_DOT, 0, 0);
		if (!yymsp[0].minor.yy50) param->memory_error = true; }
#line 1797 "parser.c"
        break;
      case 68: /* any ::= PLUS */
#line 368 "parser.y"
{ yymsp[0].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_PLUS, 0, 0);
		if (!yymsp[0].minor.yy50) param->memory_error = true; }
#line 1803 "parser.c"
        break;
      case 69: /* any ::= GT */
#line 371 "parser.y"
{ yymsp[0].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_GT, 0, 0);
		if (!yymsp[0].minor.yy50) param->memory_error = true; }
#line 1809 "parser.c"
        break;
      case 70: /* any ::= LPAREN ws any_list RPAREN */
#line 374 "parser.y"
{ if ((yymsp[-3].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_PAREN,
		                        0, 0)))
			yymsp[-3].minor.yy50->value = yymsp[-1].minor.yy50;
		else {
			param->memory_error = true;
			css_free_node(yymsp[-1].minor.yy50);
			yymsp[-3].minor.yy50 = 0;
		} }
#line 1821 "parser.c"
        break;
      case 71: /* any ::= LBRAC ws any_list RBRAC */
#line 383 "parser.y"
{ if ((yymsp[-3].minor.yy50 = css_new_node(param->stylesheet, CSS_NODE_BRAC,
		                        0, 0)))
			yymsp[-3].minor.yy50->value = yymsp[-1].minor.yy50;
		else {
			param->memory_error = true;
			css_free_node(yymsp[-1].minor.yy50);
			yymsp[-3].minor.yy50 = 0;
		} }
#line 1833 "parser.c"
        break;
      case 83: /* at_rule ::= ATKEYWORD ws any_list block */
#line 47 "parser.y"
{
}
#line 1839 "parser.c"
  yy_destructor(yypParser,39,&yymsp[-1].minor);
        break;
      case 86: /* block_body ::= block_body any ws */
#line 56 "parser.y"
{
}
#line 1846 "parser.c"
  yy_destructor(yypParser,42,&yymsp[-1].minor);
        break;
      case 90: /* declaration ::= DELIM property ws COLON ws value ws */
#line 255 "parser.y"
{
}
#line 1853 "parser.c"
  yy_destructor(yypParser,54,&yymsp[-1].minor);
        break;
      default:
      /* (73) stylesheet ::= ws statement_list */ yytestcase(yyruleno==73);
      /* (74) ws ::= */ yytestcase(yyruleno==74);
      /* (75) ws ::= ws_1 */ yytestcase(yyruleno==75);
      /* (76) ws_1 ::= S */ yytestcase(yyruleno==76);
      /* (77) ws_1 ::= ws_1 S */ yytestcase(yyruleno==77);
      /* (78) statement_list ::= */ yytestcase(yyruleno==78);
      /* (79) statement_list ::= statement_list statement */ yytestcase(yyruleno==79);
      /* (80) statement ::= ws_1 */ yytestcase(yyruleno==80);
      /* (81) statement ::= ruleset (OPTIMIZED OUT) */ assert(yyruleno!=81);
      /* (82) statement ::= at_rule (OPTIMIZED OUT) */ assert(yyruleno!=82);
      /* (84) block ::= LBRACE ws block_body RBRACE ws */ yytestcase(yyruleno==84);
      /* (85) block_body ::= */ yytestcase(yyruleno==85);
      /* (87) block_body ::= block_body block */ yytestcase(yyruleno==87);
      /* (88) block_body ::= block_body ATKEYWORD ws */ yytestcase(yyruleno==88);
      /* (89) block_body ::= block_body SEMI ws */ yytestcase(yyruleno==89);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  css_parser_ARG_FETCH
  css_parser_CTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
/************ End %parse_failure code *****************************************/
  css_parser_ARG_STORE /* Suppress warning about unused %extra_argument variable */
  css_parser_CTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  css_parser_TOKENTYPE yyminor         /* The minor type of the error token */
){
  css_parser_ARG_FETCH
  css_parser_CTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 441 "parser.y"
 param->syntax_error = true; 
#line 1933 "parser.c"
/************ End %syntax_error code ******************************************/
  css_parser_ARG_STORE /* Suppress warning about unused %extra_argument variable */
  css_parser_CTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  css_parser_ARG_FETCH
  css_parser_CTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  css_parser_ARG_STORE /* Suppress warning about unused %extra_argument variable */
  css_parser_CTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "css_parser_Alloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void css_parser_(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  css_parser_TOKENTYPE yyminor       /* The value for the token */
  css_parser_ARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  css_parser_CTX_FETCH
  css_parser_ARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor css_parser_CTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int css_parser_Fallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
