/*
 * Automatically generated by png2c
 *
 * $Id$
 */


extern const unsigned char Throbber[];
#define THROBBER_WIDTH 216
#define THROBBER_HEIGHT 24
#define THROBBER_DEPTH 24
#define THROBBER_IMAGES 9
